### PR TITLE
Check for process object

### LINKED ISSUE #78: Electron, nwjs and Brackets-Shell
Instead of detecting the browser I think that it would be better to detect a Node.js runtime since there are a number of projects that implements both.

This leads to uncaught exceptions not being fixed in Electron. Here is the offending line.

```javascript
if (installHandler && !isInBrowser()) {
  process.on('uncaughtException', handleUncaughtExceptions);
}
```

It would be better to check for the `process` object:

```javascript
if (installHandler && typeof process === 'object' && typeof process.on === 'function') {
  process.on('uncaughtException', handleUncaughtExceptions);
}
```

### PR DESCRIPTION
**Pull request by LinusU**
Fixes #78 

It also includes #76 and #77 so **please pull those before pulling this** and this pull request should automatically be updated to only show the one relevant commit.

### CODE REVIEW

**Comment by julien-f** [comment]
Can you base your PRs on master to be able to merge them independently?

**Comment by LinusU** [comment]
If you pull them in order you will be able to merge them independently.

Unfortunately all three have conflicts which is way I opted to do it like this.

**Comment by LinusU** [comment]
Actually, don't pull this one yet! I think that there is a problem we haven't counted with... I think that browserify shims `process` as a global object and since we are building with that it might not work as intended...

Whatever the reason, the tests fails in the browser for this one, so just hold on for a bit.

**Comment by julien-f** [comment]
Of course I can pull them in order but it defeat the goal of having separate PRs.

The browserify test also fails in master, I have to figure out why.

**Comment by julien-f** [comment]
And I do not think it is a problem that browserify shims `process`, it won't cause any errors.

**Comment by LinusU** [comment]
You are right, I tested in Safari instead of Chrome :facepunch: :dizzy_face: 

The tests passes.

The browserify test won't work until a bug in browserify is resolved, see #66 

I understand that it defeats the pull request but if I had did it the other way, then whenever you merged one, the other one would have changed to "unable to automatically merge" because of merge conflicts. So I opted to enforce the order in which they are merged, I hope it's okay :)

**Comment by LinusU** [comment]
Rebased on master

File: source-map-support.js [hunk 1]
```diff
@@ -21,6 +21,10 @@ function isInBrowser() {
   return ((typeof window !== 'undefined') && (typeof XMLHttpRequest === 'function'));
 }
 
+function hasGlobalProcess() {
```
Comment (julien-f) [inline source-map-support.js]: Can't we find a better name?
Because it tests more than just the presence of `process`.

File: source-map-support.js [hunk 2]
```diff
@@ -21,6 +21,10 @@ function isInBrowser() {
...
+  return ((typeof process !== 'undefined') && (typeof process.on === 'function'));
```
Comment (julien-f) [inline source-map-support.js]: It's probably a very minor risk but this code breaks if `process` is `null`.

Comment (LinusU) [inline source-map-support.js]: You're right, I have a quick fix, 2 min...

File: source-map-support.js (hunk 1 above)
Comment (LinusU) [inline source-map-support.js]: Hmm, might be a good idea. Do you have any suggestions? I don't really know what else to call it.

Comment (julien-f) [inline source-map-support.js]: `hasGlobalProcessEventListener()`?

It's far from pretty but IMHO it is a bit clearer.

Comment (LinusU) [inline source-map-support.js]: What do you think of `hasGlobalProcessEventEmitter()`? Seems a bit more correct

Comment (julien-f) [inline source-map-support.js]: Yes, my bad.

Monday morning and I am already tired :p

Comment (LinusU) [inline source-map-support.js]: Hehe, I feel exactly the same at the moment :D

**Comment by LinusU** [comment]
Done and done :+1:
